language: rust
cache: cargo
rust:
 - stable
 - beta
 - nightly
env: RUN=BUILD
before_script: rustup target add thumbv7m-none-eabi
script:
 - cargo build --release
matrix:
  include:
    - rust: stable
      env: RUN=FMT
      before_script: rustup component add rustfmt-preview
      script: cargo fmt --all -- --check
